module.exports = {
  'alpha': true,
  'alphadashed': true,
  'alphanumeric': true,
  'alphanumericdashed': true,
  'contains': true,
  'datetime': true,
  '_decimal_': true,
  'finite': true,
  'float': true,
  'hexadecimal': true,
  '_int_': true,
  'ipv4': true,
  'ipv6': true,
  '_is_': true,
  'lowercase': true,
  'notRegex': true,
  'notContains': true,
  'notNull': true,
  'numeric': true,
  'truthy': true,
  'uppercase': true,
  'urlish': true,
  'uuidv3': true,
  'uuidv4': true,
};
